### ISSUE TITLE
fzrepl: query history per command?

### ISSUE THREAD

**Issue by dufferzafar** [DanielFGray/fzf-scripts#10]
I really liked the fzrepl script.

I was wondering if we could add a way to store history of the queries used.

**Comment by DanielFGray** [comment]
I had thought about adding history support when I first created the script, but I couldn't imagine a good use case for it, as I only use fzrepl for one-shot commands.

Can you elaborate on how you would use history and what would make it useful?

**Comment by DanielFGray** [comment]
I added a commit that uses the environment variable `FZREPL_FILE` to set the `--history` file

Some example usage:

```
curl "$json_url" | jq . | FZREPL_FILE=./jqscript fzrepl 'jq -r'
```
