### ISSUE TITLE
[fzmp] Queuing  "Greatest hits" queues ALL albums with same name,

### ISSUE THREAD

**Issue by duffydack** [DanielFGray/fzf-scripts#12]
![grim-193346](https://user-images.githubusercontent.com/41839511/85890084-96e15e00-b7e4-11ea-93fd-3e71efddb501.png)

I queued up 1 album, in this case Nevermore/Greatest Hits, and it subsequently queued up all the "greatest hits" I have from all artists.

Steps to reproduce:
-  Have the same album name by multiple artists
-  F3 to artists, navigate to album, ctrl-space to add to playlist

**Comment by DanielFGray** [comment]
Wow, yeah that is a problem.

I just made a develop branch, the latest commit should have a fix, let me know if that works and I'll merge it to master

**Comment by duffydack** [comment]
Yes, works as it should, thanks.
