### ISSUE TITLE
[fzmp] "QueenAdreena" shows up in "Queen" artist view

### ISSUE THREAD

**Issue by duffydack** [DanielFGray/fzf-scripts#14]
![grim-203733](https://user-images.githubusercontent.com/41839511/93687782-3cd8f780-fab8-11ea-9109-c023f329d57a.png)

See attached.  Example of it showing all the albums for "Queen", but also showing "QueenAdreena" albums (Eleventeen and Ride a Cock Horse), plus Queensryche, and anything with else with Queen in the name.

**Comment by DanielFGray** [comment]
Been fiddling with this issue on and off for a while, and I only seem to make trade-offs, where it fixes one thing but breaks another....

**Comment by duffydack** [comment]
I thought it might be a tough one.  No matter really, I rarely use it in that view anyway, which is why I only just noticed the bug.
