### ISSUE TITLE
`igr` [bat error]: invalid digit found in string

### ISSUE THREAD

**Issue by savchenko** [DanielFGray/fzf-scripts#15]
Starting in the freshly cloned `fzf-scripts` repository:
![image](https://user-images.githubusercontent.com/300146/97278615-e89d0200-1831-11eb-825f-926d361fb6c5.png)

```
Debian 10 /  Linux 4.19.128-microsoft-standard
bat 0.15.4
fzf 0.22.0 (6f9663d)
```

**Comment by DanielFGray** [comment]
ah, I forgot to add `--ansi` to the arguments, I have it added to my `FZF_DEFAULT_OPTS`.
