### ISSUE TITLE
(!) `fzrepl` doesn't preview file content, instead tries to execute input

### ISSUE THREAD

**Issue by savchenko** [DanielFGray/fzf-scripts#16]
In `fzf-scripts` repository:

`$ ls -la | ./fzrepl`:

![image](https://user-images.githubusercontent.com/300146/97279282-b9d35b80-1832-11eb-95b8-fcd43af3593f.png)

```
Debian 10 /  Linux 4.19.128-microsoft-standard
bat 0.15.4
fzf 0.22.0 (6f9663d)
```

**Comment by DanielFGray** [comment]
`fzrepl` expects a command to be given to act as the repl, and without one given it executes the fzf query as a command.

I can push a fix that will throw an error if no command is given, would that behave as expected?

**Comment by savchenko** [comment]
> I can push a fix that will throw an error if no command is given, would that behave as expected?

I'd say yes, maybe with a small snippet of an example usage?
