### ISSUE TITLE
igr: nothing on Enter (because user need v)

### ISSUE THREAD

**Issue by vitaly-zdanevich** [DanielFGray/fzf-scripts#26]
https://github.com/DanielFGray/fzf-scripts/blob/6ed0f371abc50f41e685ea2b7cd80d3efda1a0c4/igr#L21

Replace to `vim`?

And another problem here, if I replace `v` to `vim` - it open on the first line, can it open on the target line please?

**Comment by DanielFGray** [comment]
`v` in this script is [github.com/DanielFGray/bin/v](https://github.com/DanielFGray/bin/blob/master/v)

i should probably change the default to `$EDITOR` or something similar

**Comment by vitaly-zdanevich** [comment]
> `v` in this script is [github.com/DanielFGray/bin/v](https://github.com/DanielFGray/bin/blob/master/v)

Please add a documentation to that `v` script, why do you need a wrapper around Vim? In the code I see something about Vim server?..

**Comment by vitaly-zdanevich** [comment]
> i should probably change the default to $EDITOR or something similar, and allow an override (possibly from env?)

Yep...

**Comment by vitaly-zdanevich** [comment]
By the way - I added to Guru https://github.com/gentoo/guru/tree/master/app-shells/igr

**Comment by DanielFGray** [comment]
closed by b51295e

**Comment by DanielFGray** [comment]
> By the way - I added to Guru https://github.com/gentoo/guru/tree/master/app-shells/igr
> 
> [With my patch](https://github.com/gentoo/guru/blob/master/app-shells/igr/files/vim-open-current-line.patch)

your patch is probably broken now

**Comment by vitaly-zdanevich** [comment]
Thanks! Now we have full context!
