### ISSUE TITLE
fzmp - playlists menu and 'clear playlist' key

### ISSUE THREAD

**Issue by duffydack** [DanielFGray/fzf-scripts#9]
First off, this is brilliant.  I've not touched ncmpcpp since.  Only thing I would like to request is to have a menu (an F key same as rest) to list the users playlists, with the ability to select/load it.

Also, the option to quickly clear the currently playing playlist.  With `fzf -m` I can select multiple entries which is nice, but a quicker clear all option (other than a terminal `mpc clear`) would be welcome.

_edit:_  Just thought of 1 more.  Like ctrl-space adds to playlist in 'artists' view, maybe have ctrl-enter to queue tagged (using `fzf -m`) / selected entries in 'songs' and 'artists' view ?

**Comment by DanielFGray** [comment]
Thanks for the kind words!

Playlists would be great feature to have, I'll look into it soon

Regarding clearing the current playlist, the last section of the `--help` mentions adding an export in your terminal's profile:

```
--bind="ctrl-t:toggle-all"
```

With this, `Ctrl-t` will invert the current selection, which would select everything if you have nothing selected, and then you can remove those items from the playlist like normal with `Ctrl-d`.  
Perhaps the wording in the `--help` could be changed to make this easier to understand?

I'll look into adding queueing, but I remember there being some kind of trouble when I first thought of it.

**Comment by duffydack** [comment]
I didn't notice that ctrl-t, but that doesn't seem to do anything, maybe because I use fzf's zsh keybinds (ctrl-r/ctrl-t)?  Well I changed it to ctrl-a `fzf_options +s -e -i --reverse --cycle --bind="ctrl-a:toggle-all"` and still not working.  I'm missing something, as usual.

Playlist option would be great.  Ability to queue it, or replace current if possible too.

**Comment by DanielFGray** [comment]
I pushed a few commits, test them out, let me know your thoughts.

**Comment by duffydack** [comment]
Very nice.  It's exactly what I wanted.  Can now queue instead of adding/playing.  Even a save playlist, nice.

Been trying to get the ctrl-a:toggle-all key to work, used the full line in --help but not happening unless "ctrl-a:toggle-all" is the only option I specify.  The full line I'm using is

`export FZMP_FZF_OPTIONS="--bind="ctrl-a:toggle-all" --height=100% +s -e -i --reverse --cycle"`

Minor issue tho, I can live without it.

**Comment by DanielFGray** [comment]
```
export FZMP_FZF_OPTIONS="--bind='ctrl-a:toggle-all' --height=100% +s -e -i --reverse --cycle"
```

I changed the inner quotes around the `ctrl-a:toggle-all` to use single quotes since they were nested inside the double quotes

Personally, I define this bind in my `~/.profile` as part of `FZF_DEFAULT_OPTS` so that I can always use `ctrl-t` in fzf to invert the selection. There should be no issue clashing with fzf keybindings for `ctrl-t` in your shell.

**Comment by duffydack** [comment]
Jeez, why didn't I just think of that, I even have some FZF_DEFAULT_OPTS set.  Ok, working now, thanks

**Comment by duffydack** [comment]
_btw,_ I have added this to the aur dumpster fire (fzmp-git), for my own sanity tracking files on my system :)
